.\"
.TH 7zz "1" "Jan 2024" "23.01"
.SH NAME
7zz - 7-Zip file archiver with a high compression ratio (standalone)
.SH SYNOPSIS
.SY 7zz
\fI\,command\/\fR
[\fI\,switches\/\fR\&.\|.\|.\&]
\fI\,archive_name\/\fR
[\fI\,file_names\/\fR]
[@\fI\,listfile\/\fR]
.YS
.SH DESCRIPTION
7-Zip file archiver with a high compression ratio
.SH SEE ALSO
7z(1), 7-Zip
.UR https://\:www.7-zip.org/
.UE
.SH COPYRIGHT
Copyright \(co 1999\-2023 Igor Pavlov.
.br
Distributed under the LGPL-2.1+ license.
